name: Auto-create PR based on comment

on:
  issue_comment:
    types: [created]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'major') || contains(github.event.comment.body, 'minor') || contains(github.event.comment.body, 'patch')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: exp

      - name: Create new branch
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          NEW_BRANCH_NAME="version-bump-$COMMENT_BODY-${{ github.run_id }}"
          git checkout -b $NEW_BRANCH_NAME

      - name: Update version based on comment
        run: |
          # Setup git user
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<eng@channel.io>"
          
          COMMENT_BODY="${{ github.event.comment.body }}"
          NEW_VERSION=${npm --no-git-tag-version version $COMMENT_BODY}
          echo "New Version is $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git add package.json
          git commit -n -m "Bump Version"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          NEW_BRANCH_NAME="version-bump-$COMMENT_BODY-${{ github.run_id }}"
          gh pr create --base exp --head $NEW_BRANCH_NAME --title "Version bump to $COMMENT_BODY ($NEW_VERSION)" --body "Automated version bump"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
