name: Auto-create PR based on comment

on:
  issue_comment:
    types: [created]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'major') || contains(github.event.comment.body, 'minor') || contains(github.event.comment.body, 'patch')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version based on comment
        run: |
          # Setup git user
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<eng@channel.io>"
          
          COMMENT_BODY="${{ github.event.comment.body }}"
          if [[ "$COMMENT_BODY" == "major" ]]; then
            npm version major
          elif [[ "$COMMENT_BODY" == "minor" ]]; then
            npm version minor
          elif [[ "$COMMENT_BODY" == "patch" ]]; then
            npm version patch
          fi

      - name: Push Changes
        run: git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        run: gh pr create --base exp --head HEAD --title "Version bump to $COMMENT_BODY" --body "Automated version bump"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
